name: configuration-file-releaser
description: A Github action for releasing a new version using configuration files from your project
branding:
  icon: anchor
  color: orange
inputs:
  repository:
    description: The repository name in full
    required: true
outputs:
  id:
    description: Latest release ID
  release:
    description: Latest release name
runs:
  using: "node16"
  main: "dist/index.js"
