name: configuration-file-releaser
description: A Github action for releasing a new version using configuration files from your project
branding:
  icon: anchor
  color: orange
inputs:
  repository:
    description: The repository name in full
    required: true
  loader:
    description: The type of the file
    required: true
  configurationFile:
    description: The configuration file
    required: false
outputs:
  id:
    description: Latest release ID
  currentRelease:
    description: Latest release name
  nextRelease:
    description: Next release name
  shouldGenerateNewRelease:
    description: True if you need to generate a new version
runs:
  using: "node16"
  main: "dist/index.js"
