name: "release"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v3

      - id: releaser
        name: Configuration File Releaser
        uses: thiagodonferreira/configuration-file-releaser@main
        with:
          loader: nodejs
          configurationFile: ./package.json

      - run: node --print 'process.env'

      - name: Create Release on Github
        uses: softprops/action-gh-release@v1
        if: ${{steps.releaser.outputs.shouldGenerateANewVersion }}
        with:
          name: ${{ steps.releaser.outputs.nextRelease }}
          tag_name: v${{steps.releaser.outputs.nextRelease}}
          # files: "*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
